version: '3'
services:
  web_blue:
    container_name: web_blue
    image: haeun1107/rangers:previous  # 이전 버전 또는 현재 운영 중인 버전
    ports:
      - 8081:8080  # 호스트의 8081 포트를 컨테이너의 8080 포트에 매핑

  web_green:
    container_name: web_green
    image: haeun1107/rangers:latest  # 새로운 버전
    ports:
      - 8082:8080  # 호스트의 8082 포트를 컨테이너의 8080 포트에 매핑

  nginx:
    container_name: nginx
    image: haeun1107/rangers-nginx
    ports:
      - 80:80
    depends_on:
      - web_blue
      - web_green