#green
version: '3'
services:
  backend:
    build: .
    ports:
      - "8082:8080"
    container_name: spring-green

    environment:
      - RDS_HOST=${RDS_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}